"""
MD Workflow Programmer Agent

Generates executable scripts for MD simulations based on planner requests.
Scripts are generated in /temp directory for human review before deployment.
Only communicates with Planner agent, not Supervisor.
"""
import logging
import os
import json
import yaml
from pathlib import Path
from typing import Dict, Any, Optional, List
from ..state import MDState
from ..llm import LLMClient
from ..utils import log_supervisor_routing

logger = logging.getLogger(__name__)


class MDProgrammer:
    """
    Programmer agent that generates MD workflow scripts based on planner specifications.
    Scripts are created in a temporary directory for human review and approval.
    Communicates only with MDPlanner, not directly with Supervisor.
    """
    
    def __init__(self, llm_client: LLMClient, config_path: Optional[str] = None):
        if llm_client is None:
            raise ValueError("llm_client is required")
        
        self.llm = llm_client
        self.config_path = config_path or os.path.join(
            os.path.dirname(__file__), "config.yaml"
        )
        
        # Load programmer configuration
        self.config = self._load_config()
        
        # Initialize temp directory for generated scripts
        self.temp_dir = Path("/tmp/md_scripts")
        self.temp_dir.mkdir(parents=True, exist_ok=True)
        
        # Load script templates
        self.templates = self._load_templates()
        
        logger.info(f"MD Programmer initialized. Temp dir: {self.temp_dir}")
    
    def _load_config(self) -> Dict[str, Any]:
        """Load programmer configuration."""
        if os.path.exists(self.config_path):
            with open(self.config_path, 'r') as f:
                return yaml.safe_load(f) or {}
        else:
            logger.warning(f"Config file {self.config_path} not found, using defaults")
            return self._get_default_config()
    
    def _get_default_config(self) -> Dict[str, Any]:
        """Default programmer configuration."""
        return {
            "programmer": {
                "output_directory": "/tmp/md_scripts",
                "require_human_review": True,
                "auto_format_code": True,
                "include_documentation": True,
                "include_error_handling": True
            },
            "supported_script_types": [
                "gromacs_topology",
                "gromacs_mdp",
                "gromacs_solvation",
                "gromacs_minimization",
                "gromacs_equilibration",
                "gromacs_production",
                "analysis_script",
                "preprocessing_script",
                "slurm_job_script",
                "visualization_script"
            ],
            "code_quality": {
                "include_type_hints": True,
                "include_docstrings": True,
                "max_line_length": 100,
                "code_style": "pep8"
            }
        }
    
    def _load_templates(self) -> Dict[str, str]:
        """Load script templates."""
        templates_dir = Path(os.path.dirname(__file__)) / "templates"
        templates = {}
        
        if templates_dir.exists():
            for template_file in templates_dir.glob("*.template"):
                template_name = template_file.stem
                with open(template_file, 'r') as f:
                    templates[template_name] = f.read()
        else:
            logger.info("Templates directory not found, using default templates")
            templates = self._get_default_templates()
        
        return templates
    
    def _get_default_templates(self) -> Dict[str, str]:
        """Default script templates."""
        return {
            "gromacs_topology": """
# GROMACS Topology Generation Script
# Generated by MD Programmer Agent
# @PDB_FILE@
# @FORCE_FIELD@

set -e

PDB_FILE="$1"
FF="$2"
OUTPUT_DIR="$3"

echo "Generating topology for $PDB_FILE using $FF force field..."

# Create working directory
mkdir -p "$OUTPUT_DIR"
cd "$OUTPUT_DIR"

# Run pdb2gmx
gmx pdb2gmx -f "$PDB_FILE" -o processed.gro -p topol.top -ff "$FF" -water tip3p -ignh << EOF
1
EOF

echo "Topology generation complete!"
echo "Output files:"
echo "  - processed.gro: Processed coordinates"
echo "  - topol.top: System topology"
""",
            
            "gromacs_mdp": """
# GROMACS Molecular Dynamics Parameter File
; Generated by MD Programmer Agent
; @SIMULATION_TYPE@

; Run parameters
integrator = @INTEGRATOR@
dt = @TIMESTEP@
nsteps = @NSTEPS@

; Output control
nstenergy = 1000
nstlog = 1000
nstxout-compressed = 1000

; Neighbour searching
nstlist = 10
ns_type = grid
pbc = xyz

; Electrostatics
coulombtype = PME
rcoulomb = 1.0
ewald_rtol = 1e-05

; VDW
rvdw = 1.0
DispCorr = EnerPres

; Temperature control
tcoupl = V-rescale
tc-grps = System
tau_t = 0.1
ref_t = 298.15

; Pressure control
pcoupl = Parrinello-Rahman
pcoupltype = isotropic
tau_p = 2.0
ref_p = 1.0
compressibility = 4.5e-5
""",
            
            "preprocessing_script": """
#!/usr/bin/env python3
\"\"\"
PDB Preprocessing Script
Generated by MD Programmer Agent
\"\"\"

import argparse
import logging
from pathlib import Path
from Bio import PDB

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def preprocess_pdb(pdb_file: str, output_file: str, remove_water: bool = True,
                   add_hydrogens: bool = True):
    \"\"\"
    Preprocess PDB file for MD simulation.
    
    Args:
        pdb_file: Input PDB file
        output_file: Output PDB file
        remove_water: Remove water molecules
        add_hydrogens: Add missing hydrogen atoms
    \"\"\"
    logger.info(f"Preprocessing {pdb_file}...")
    
    # Load PDB
    parser = PDB.PDBParser(QUIET=True)
    structure = parser.get_structure('protein', pdb_file)
    
    # Remove water if requested
    if remove_water:
        model = structure[0]
        chains_to_remove = []
        for chain in model:
            for residue in list(chain):
                if residue.get_resname() in ['HOH', 'WAT']:
                    chain.detach_child(residue.get_id())
        logger.info("Removed water molecules")
    
    # Save processed structure
    io = PDB.PDBIO()
    io.set_structure(structure)
    io.save(output_file)
    logger.info(f"Saved processed structure to {output_file}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Preprocess PDB for MD")
    parser.add_argument("pdb_file", help="Input PDB file")
    parser.add_argument("-o", "--output", default="processed.pdb",
                       help="Output PDB file")
    parser.add_argument("--keep-water", action="store_true",
                       help="Keep water molecules")
    
    args = parser.parse_args()
    preprocess_pdb(args.pdb_file, args.output, 
                   remove_water=not args.keep_water)
""",
            
            "slurm_job_script": """
#!/bin/bash
#SBATCH --job-name=@JOB_NAME@
#SBATCH --partition=@PARTITION@
#SBATCH --nodes=@NODES@
#SBATCH --ntasks-per-node=@TASKS_PER_NODE@
#SBATCH --cpus-per-task=@CPUS_PER_TASK@
#SBATCH --mem=@MEMORY@
#SBATCH --time=@TIME_LIMIT@
#SBATCH --output=@JOB_NAME@.%j.out
#SBATCH --error=@JOB_NAME@.%j.err

# SLURM Job Script
# Generated by MD Programmer Agent

echo "Job started on $(hostname) at $(date)"
echo "SLURM Job ID: $SLURM_JOB_ID"

# Load modules
module load gromacs
module load gcc

# Change to working directory
cd $SLURM_SUBMIT_DIR

# Run simulation
echo "Starting simulation..."
mpirun gmx_mpi mdrun -v -deffnm @SIMULATION_NAME@ -ntomp @CPUS_PER_TASK@

echo "Job completed at $(date)"
"""
        }
    
    def programmer_node(self, state: MDState) -> MDState:
        """
        Main programmer node. Generates scripts based on planner's execution plan.
        Only called by Planner when scripts are needed.
        """
        logger.info("Programmer node: Generating execution scripts from approved plan")
        
        # Get approved plan and scripts to generate
        plan = state.get("execution_plan", {})
        scripts_needed = plan.get("programmer_scripts", [])
        
        if not scripts_needed:
            logger.info("No scripts needed for this plan")
            state["next_node"] = "planner"
            return state
        
        # Generate each required script
        generated_scripts = {}
        script_errors = []
        
        for script_type in scripts_needed:
            try:
                script_info = self._generate_script(script_type, state)
                generated_scripts[script_type] = script_info
                logger.info(f"Generated script: {script_type}")
            except Exception as e:
                error_msg = f"Error generating {script_type}: {e}"
                logger.error(error_msg)
                script_errors.append(error_msg)
        
        # Store generated scripts in state
        state["generated_scripts"] = generated_scripts
        state["scripts_awaiting_review"] = True
        state["script_generation_errors"] = script_errors if script_errors else []
        
        # Route back to planner for human review coordination
        state["next_node"] = "planner"
        state["planner_action"] = "review_scripts"
        state["scripts_for_review"] = {
            script_type: {
                "file_path": info.get("file_path"),
                "preview": info.get("preview", ""),
                "purpose": info.get("purpose", "")
            }
            for script_type, info in generated_scripts.items()
        }
        
        log_supervisor_routing(
            state, "planner",
            f"Programmer generated {len(generated_scripts)} scripts. Routing back to planner for review coordination."
        )
        
        return state
    
    def _generate_script(self, script_type: str, state: MDState) -> Dict[str, Any]:
        """
        Generate a specific script based on type and state.
        """
        logger.info(f"Programmer: Generating script type '{script_type}'")
        
        # Use LLM to generate script with specifications
        prompt = self._build_script_generation_prompt(script_type, state)
        
        # Generate script content
        script_content = self.llm.prompt(
            prompt,
            system="You are an expert MD simulation script programmer. Generate production-ready scripts with proper error handling, documentation, and best practices."
        )
        
        # Save script to temp directory
        script_info = self._save_script(script_type, script_content, state)
        
        # Log script generation
        self._log_script_generation(script_type, prompt, script_content)
        
        return script_info
    
    def _build_script_generation_prompt(self, script_type: str, state: MDState) -> str:
        """Build prompt for script generation."""
        
        execution_plan = state.get("execution_plan", {})
        pdb_file = state.get("raw_pdb", "input.pdb")
        working_dir = state.get("working_directory", "/tmp")
        
        base_prompt = f"""
Generate a production-ready {script_type} script for MD simulation.

CONTEXT FROM PLANNER:
- PDB File: {pdb_file}
- Working Directory: {working_dir}
- Force Field: {state.get('force_field', 'amber99sb-ildn')}
- MD Engine: {state.get('md_engine', 'gromacs')}
- Water Model: {state.get('water_model', 'tip3p')}

EXECUTION PLAN:
{json.dumps(execution_plan, indent=2)}

REQUIREMENTS:
1. Include comprehensive error handling and logging
2. Add inline documentation explaining key steps
3. Make the script parameterizable with command-line arguments
4. Include usage instructions in comments
5. Follow best practices for {script_type}
6. Include validation steps where appropriate
7. Add progress reporting and status messages

SCRIPT TYPE SPECIFICS:
"""
        
        # Add type-specific requirements
        type_specifics = {
            "gromacs_topology": """
- Generate GROMACS topology from PDB
- Use specified force field
- Include water model selection
- Output: topol.top and processed.gro
- Handle missing atoms gracefully
""",
            "gromacs_mdp": """
- Create GROMACS parameter file
- Include proper integrator settings
- Set appropriate timestep
- Configure output frequency
- Include thermostat and barostat
- Add energy conservation checks
""",
            "preprocessing_script": """
- Clean PDB file (remove waters, add H)
- Fix missing residues
- Validate structure
- Output cleaned PDB
- Provide summary statistics
""",
            "slurm_job_script": """
- Create SLURM job submission script
- Set appropriate resource allocation
- Include module loading
- Configure job monitoring
- Include error checking
- Provide job status output
""",
            "analysis_script": """
- Analyze MD trajectory
- Calculate requested metrics (RMSD, RMSF, etc.)
- Generate plots
- Provide statistical summary
- Include data validation
"""
        }
        
        prompt = base_prompt + type_specifics.get(script_type, "")
        
        return prompt
    
    def _save_script(self, script_type: str, content: str, state: MDState) -> Dict[str, Any]:
        """Save generated script to temp directory."""
        
        # Determine file extension
        extensions = {
            "gromacs_topology": ".sh",
            "gromacs_mdp": ".mdp",
            "gromacs_solvation": ".sh",
            "preprocessing_script": ".py",
            "slurm_job_script": ".sh",
            "analysis_script": ".py"
        }
        
        ext = extensions.get(script_type, ".sh")
        
        # Create filename
        filename = f"{script_type}_{state.get('plan_version', 1)}{ext}"
        file_path = self.temp_dir / filename
        
        # Make scripts executable if shell script
        mode = 0o755 if ext in [".sh", ""] else 0o644
        
        # Write to file
        with open(file_path, 'w') as f:
            f.write(content)
        
        os.chmod(file_path, mode)
        
        # Create script info
        script_info = {
            "script_type": script_type,
            "file_path": str(file_path),
            "filename": filename,
            "size_bytes": len(content),
            "content": content,
            "preview": content[:500] + "..." if len(content) > 500 else content,
            "executable": ext in [".sh", ""],
            "purpose": self._get_script_purpose(script_type),
            "generated_at": Path(file_path).stat().st_mtime
        }
        
        logger.info(f"Saved script to {file_path} ({len(content)} bytes)")
        
        return script_info
    
    def _get_script_purpose(self, script_type: str) -> str:
        """Get human-readable purpose of script."""
        purposes = {
            "gromacs_topology": "Generate GROMACS topology from PDB file",
            "gromacs_mdp": "GROMACS molecular dynamics parameters file",
            "gromacs_solvation": "Add solvent and ions to system",
            "gromacs_minimization": "Energy minimization run",
            "gromacs_equilibration": "System equilibration",
            "gromacs_production": "Production MD simulation",
            "analysis_script": "Analyze MD trajectory",
            "preprocessing_script": "Preprocess PDB file for simulation",
            "slurm_job_script": "Submit job to HPC cluster",
            "visualization_script": "Visualize structures and results"
        }
        return purposes.get(script_type, "Custom MD script")
    
    def _log_script_generation(self, script_type: str, prompt: str, response: str):
        """Log script generation for audit."""
        logger.info(f"PROGRAMMER_{script_type.upper()}_GENERATED")
        logger.debug(f"Prompt preview: {prompt[:200]}...")
        logger.debug(f"Generated {len(response)} bytes of code")
    
    def handle_planner_script_review(self, state: MDState) -> MDState:
        """
        Handle planner feedback on generated scripts.
        Scripts are reviewed through planner before human approval.
        """
        feedback = state.get("planner_script_feedback", "")
        
        if not feedback:
            logger.warning("No feedback from planner provided")
            return state
        
        # Check approval from planner
        if "approved" in feedback.lower() or "ready" in feedback.lower():
            logger.info("Scripts approved by planner for human review")
            state["scripts_approved_by_planner"] = True
            state["next_node"] = "human_script_review"
            log_supervisor_routing(
                state, "human_script_review",
                "Planner approved scripts. Routing to human for final review."
            )
            return state
        
        # Check modification requests
        if "modify" in feedback.lower() or "regenerate" in feedback.lower():
            logger.info("Planner requested script modifications")
            
            # Extract which scripts need modification
            scripts_to_modify = self._extract_scripts_to_modify(feedback, state)
            
            # Regenerate specified scripts
            for script_type in scripts_to_modify:
                try:
                    script_info = self._regenerate_script(script_type, feedback, state)
                    state["generated_scripts"][script_type] = script_info
                except Exception as e:
                    logger.error(f"Error regenerating {script_type}: {e}")
            
            # Request planner review again
            state["scripts_awaiting_review"] = True
            state["next_node"] = "planner"
            state["planner_action"] = "review_scripts"
            logger.info(f"Regenerated {len(scripts_to_modify)} scripts based on planner feedback")
            return state
        
        # Check rejection
        if "reject" in feedback.lower() or "cancel" in feedback.lower():
            logger.error("Planner rejected the scripts")
            state["errors"].append("Planner rejected generated scripts")
            state["next_node"] = "planner"
            return state
        
        # Default to approval for human review
        state["scripts_approved_by_planner"] = True
        state["next_node"] = "human_script_review"
        return state
    
    def _extract_scripts_to_modify(self, feedback: str, state: MDState) -> List[str]:
        """Extract which scripts need modification from feedback."""
        scripts = list(state.get("generated_scripts", {}).keys())
        
        # Simple heuristic: if feedback mentions a script name, mark for modification
        scripts_to_modify = []
        for script in scripts:
            if script in feedback.lower():
                scripts_to_modify.append(script)
        
        return scripts_to_modify if scripts_to_modify else scripts
    
    def _regenerate_script(self, script_type: str, feedback: str, state: MDState) -> Dict[str, Any]:
        """Regenerate a script based on planner feedback."""
        
        prompt = f"""
Regenerate the {script_type} script based on the following feedback from planner:

FEEDBACK:
{feedback}

CONTEXT:
- PDB File: {state.get('raw_pdb')}
- Force Field: {state.get('force_field')}

Create an improved version addressing the feedback while maintaining all original requirements.
"""
        
        script_content = self.llm.prompt(
            prompt,
            system="You are an expert MD script programmer. Improve scripts based on planner feedback."
        )
        
        script_info = self._save_script(script_type, script_content, state)
        return script_info