"""Analysis summary reading functionality"""
import json
import logging
from typing import Dict, Any, Optional
from pathlib import Path
from datetime import datetime
from langchain.tools import tool

logger = logging.getLogger(__name__)


@tool
def read_analysis_summary(
    summary_file: str,
    working_dir: Optional[str] = None
) -> Dict[str, Any]:
    """
    Read and parse analysis_summary.jsonl file.
    
    Extracts all analysis results, statistics, and metadata from the
    JSONL file generated by the analysis agent.
    
    Args:
        summary_file: Path to analysis_summary.jsonl (can be filename or full path)
        working_dir: Working directory (if summary_file is relative)
    
    Returns:
        Dict with parsed analysis entries and summary statistics
    """
    # Resolve input path
    summary_path = Path(summary_file)
    if not summary_path.is_absolute() and working_dir:
        summary_path = Path(working_dir) / summary_file
    
    # If file doesn't exist, try common subdirectories
    if not summary_path.exists() and working_dir:
        # Try analysis/ subdirectory (most common location)
        alt_path = Path(working_dir) / "analysis" / Path(summary_file).name
        if alt_path.exists():
            logger.info(f"Found analysis summary in analysis/ subdirectory: {alt_path}")
            summary_path = alt_path
        else:
            # Try searching recursively in working_dir
            working_path = Path(working_dir)
            matches = list(working_path.rglob(Path(summary_file).name))
            if matches:
                logger.info(f"Found analysis summary at: {matches[0]}")
                summary_path = matches[0]
    
    if not summary_path.exists():
        logger.error(f"Analysis summary file not found: {summary_path}")
        logger.error(f"Searched in: {summary_path.parent} and subdirectories")
        return {
            "success": False,
            "error": f"File not found: {summary_path}",
            "entries": [],
            "summary": {}
        }
    
    try:
        entries = []
        with open(summary_path, 'r') as f:
            content = f.read()
        
        # Handle multiple formats:
        # 1. Standard JSONL (one JSON per line)
        # 2. Pretty-printed JSON blocks separated by "---" delimiters
        # 3. Single large JSON array
        
        if '---' in content or '\n{' in content:
            # Split by "---" separator or parse as concatenated JSON blocks
            blocks = [b.strip() for b in content.split('---') if b.strip()]
            for block in blocks:
                try:
                    entry = json.loads(block)
                    # Skip header/metadata block
                    if "summary_file_version" not in entry and "analysis_type" in entry:
                        entries.append(entry)
                    elif "summary_file_version" in entry:
                        pass  # header - skip
                    else:
                        entries.append(entry)
                except json.JSONDecodeError:
                    pass  # skip malformed blocks
        else:
            # Standard JSONL: one JSON per line
            for line in content.splitlines():
                line = line.strip()
                if line:
                    try:
                        entry = json.loads(line)
                        entries.append(entry)
                    except json.JSONDecodeError:
                        pass
        
        # Summarize analysis types
        analysis_types = {}
        for entry in entries:
            atype = entry.get("analysis_type", "unknown")
            if atype not in analysis_types:
                analysis_types[atype] = 0
            analysis_types[atype] += 1
        
        logger.info(f"Read {len(entries)} analysis entries from {summary_path}")
        
        return {
            "success": True,
            "file_path": str(summary_path),
            "total_entries": len(entries),
            "entries": entries,
            "analysis_types": analysis_types,
            "timestamp": datetime.now().isoformat()
        }
        
    except Exception as e:
        logger.error(f"Error reading analysis summary: {e}", exc_info=True)
        return {
            "success": False,
            "error": str(e),
            "entries": [],
            "summary": {}
        }
