#!/usr/bin/env bash
# Clean + full rebuild of globalMSA_KAPCAPoc_consensusFEL-RMSF_wrapped
# after the COM (no per-group wrap) fix. Recomputes MSA → pocket → FEL →
# RMSF → cluster → draft figures so classification uses corrected COM/bound.
#
# Usage:
#   nohup bash scripts/rebuild_globalMSA_kapca_wrapped.sh \
#     > docs/ment/globalMSA_KAPCAPoc_consensusFEL-RMSF_wrapped/rebuild.log 2>&1 &
#
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"

OUT_DIR="$REPO/docs/ment/globalMSA_KAPCAPoc_consensusFEL-RMSF_wrapped"
PY="${HOME}/conda_envs/ollama_env/bin/python"
PIPE_WORKERS="${PIPE_WORKERS:-48}"
SKIP_WRAP="${SKIP_WRAP:-1}"   # mdWrap already present; set 0 to re-check wraps
WRAP_WORKERS="${WRAP_WORKERS:-8}"

if [[ ! -x "$PY" ]]; then
  echo "ERROR: python not found at $PY" >&2
  exit 1
fi
if [[ ! -d "$OUT_DIR" ]]; then
  echo "ERROR: missing $OUT_DIR" >&2
  exit 1
fi

export PATH="${HOME}/conda_envs/ollama_env/bin:${PATH}"
export LD_LIBRARY_PATH="${HOME}/conda_envs/ollama_env/lib"
export PYTHONPATH="$REPO"
export MAFFT_BINARIES="${MAFFT_BINARIES:-/apps/eb/MAFFT/7.526-GCC-13.2.0-with-extensions/libexec/mafft}"
export MPLBACKEND=Agg
unset PYTHONHOME 2>/dev/null || true

echo "================================================================"
echo "CLEAN + REBUILD globalMSA KAPCA wrapped"
echo "  out:          $OUT_DIR"
echo "  pipe_workers: $PIPE_WORKERS"
echo "  skip_wrap:    $SKIP_WRAP"
echo "  start:        $(date -Is)"
echo "================================================================"

echo ""
echo "=== Clean previous analysis artefacts (keep scripts) ==="
cd "$OUT_DIR"
# Directories regenerated by the pipeline / figure suite
rm -rf reference_pocket consensus_local_fel consensus_rmsf clustering output __pycache__
# MSA / pocket definition / manifests / logs from prior runs
rm -f \
  global_msa_alignment.json \
  global_msa_consensus_cov50.fasta \
  global_msa_full.fasta \
  global_msa_residue_map.csv \
  kapca_pocket_definition.json \
  kapca_pocket_residue_map.csv \
  msa_meta.json \
  reference_pocket_batch_manifest.json \
  pipeline.log \
  recalc_com.log \
  output_figures.log \
  README.md
cd "$REPO"
echo "Cleaned."

N_WRAP=$(ls -1 "$REPO"/pseudoKin/*/hpc/mdWrap.xtc 2>/dev/null | wc -l | tr -d ' ')
echo "mdWrap.xtc present: $N_WRAP / 38"
if [[ "$N_WRAP" -lt 38 ]]; then
  echo "WARNING: expected 38 wraps; found $N_WRAP — running wrap step"
  SKIP_WRAP=0
fi

if [[ "$SKIP_WRAP" != "1" ]]; then
  echo ""
  echo "=== Step 0: Protein+ATP wrap ==="
  "$PY" "$REPO/scripts/wrap_pseudokin_protein_atp.py" \
    --max-workers "$WRAP_WORKERS" --ligand ATP --dt 100
fi

echo ""
echo "=== Steps 1–6: MSA → pocket → FEL → RMSF → cluster ==="
"$PY" "$OUT_DIR/run_pipeline.py" \
  --steps msa,pocket_definition,fast_pocket,fel,rmsf,cluster \
  --workers "$PIPE_WORKERS" \
  --overwrite-fel \
  --overwrite-rmsf

echo ""
echo "=== Update draft representatives from new medoids ==="
"$PY" - <<'PY'
import json
from pathlib import Path

out = Path("docs/ment/globalMSA_KAPCAPoc_consensusFEL-RMSF_wrapped")
clust = json.loads((out / "clustering" / "hybrid_clusters_minmax.json").read_text())
reps = clust.get("cluster_representatives") or {}
names = clust.get("cluster_archetype_names") or {}
colors = {
    1: "#E41A1C",
    2: "#377EB8",
    3: "#4DAF4A",
    4: "#FF7F00",
    5: "#984EA3",
}
lines = [
    '"""Manuscript representatives for KAPCA global-MSA min–max clustering (k=5).',
    "",
    "Medoids from Protein+ATP wrapped re-run (corrected COM, no per-group wrap).",
    '"""',
    "",
    "from __future__ import annotations",
    "",
    "from typing import Dict",
    "",
    "DRAFT_REPRESENTATIVES: Dict[int, Dict[str, str]] = {",
]
for cid in sorted(int(k) for k in reps):
    r = reps[str(cid)]
    arch = names.get(str(cid), f"Cluster {cid}")
    lines.append(
        f'    {cid}: {{"label": "{r["label"]}", "display_name": "{r["display_name"]}"}},  # {arch}'
    )
lines += [
    "}",
    "",
    "CLUSTER_COLORS = {",
]
for cid, col in colors.items():
    lines.append(f'    {cid}: "{col}",')
lines += [
    "}",
    "",
    "CLUSTER_SHORT = {",
]
for cid in sorted(int(k) for k in names):
    lines.append(f'    {cid}: "{names[str(cid)]}",')
lines += [
    "}",
    "",
    'GROUND_TRUTH_DISPLAY_NAMES = ("EGFR", "KAPCA", "CDK2", "MK01", "AKT3")',
    "",
]
(out / "draft_representatives.py").write_text("\n".join(lines) + "\n")
print("Updated draft_representatives.py")
for cid in sorted(int(k) for k in reps):
    r = reps[str(cid)]
    print(f"  C{cid}: {r['display_name']} ({r['label']}) — {names.get(str(cid))}")
PY

echo ""
echo "=== Post plots + draft figures ==="
"$PY" "$OUT_DIR/plot_outputs.py"
"$PY" "$OUT_DIR/generate_all_draft_figures.py"

# Refresh output README
cat > "$OUT_DIR/output/README.md" <<'EOF'
# KAPCA global-MSA · wrapped traj · corrected COM

Full rebuild after removing per-group `AtomGroup.wrap` before pocket/ligand COM.
Classification: min–max Ward k=5 on corrected pocket + consensus FEL + RMSF features.
EOF

echo ""
echo "================================================================"
echo "DONE $(date -Is)"
echo "Panel:  $OUT_DIR/clustering/hybrid_dendrogram_heatmap_minmax.png"
echo "Fig3:   $OUT_DIR/output/fig3_dendrogram_heatmap.png"
echo "COM:    $OUT_DIR/output/fig4_supp_com_by_cluster.png"
echo "================================================================"
