"""
Dynamic Tool Loader for Programmer-Generated Tools

Discovers and loads tools generated by the programmer agent at runtime,
making them available to all field agents (analysis, hpc, etc.).
"""
import os
import sys
import importlib.util
import inspect
import logging
from pathlib import Path
from typing import Dict, Any, List, Optional, Callable

logger = logging.getLogger(__name__)


class DynamicToolLoader:
    """
    Loads programmer-generated tools from working_dir/programmer/ 
    and makes them available to field agents.
    """
    
    def __init__(self, programmer_dir: str = "working_dir/programmer"):
        """
        Initialize dynamic tool loader.
        
        Args:
            programmer_dir: Directory containing programmer-generated tools
        """
        # Convert to absolute path to prevent issues when cwd changes
        if not Path(programmer_dir).is_absolute():
            programmer_dir = str(Path.cwd() / programmer_dir)
        
        self.programmer_dir = Path(programmer_dir)
        self.loaded_tools: Dict[str, Callable] = {}
        self.tool_metadata: Dict[str, Dict[str, Any]] = {}
        
        # Ensure programmer directory exists to avoid warnings
        self.programmer_dir.mkdir(parents=True, exist_ok=True)
        
        logger.info(f"DynamicToolLoader initialized for: {self.programmer_dir}")
    
    def discover_and_load_tools(self) -> Dict[str, Callable]:
        """
        Discover all Python tools in programmer directory and load them.
        
        Returns:
            Dict mapping tool names to callable functions
        """
        if not self.programmer_dir.exists():
            # This should rarely happen since __init__ creates the directory
            logger.debug(f"Programmer directory still doesn't exist (creating): {self.programmer_dir}")
            self.programmer_dir.mkdir(parents=True, exist_ok=True)
        
        logger.info(f"Scanning for programmer-generated tools in: {self.programmer_dir}")
        
        # Scan for Python files in programmer directory
        python_files = list(self.programmer_dir.glob("*.py"))
        
        # Also check python subdirectory for backward compatibility
        python_dir = self.programmer_dir / "python"
        if python_dir.exists():
            python_files.extend(python_dir.glob("*.py"))
            logger.info(f"  Also scanning python subdirectory: {python_dir}")
        
        for py_file in python_files:
            if py_file.name.startswith("_") or py_file.name == "__init__.py":
                continue
            
            self._load_tool_from_file(py_file)
        
        logger.info(f"Loaded {len(self.loaded_tools)} programmer-generated tools")
        return self.loaded_tools
    
    def _load_tool_from_file(self, file_path: Path) -> Optional[Callable]:
        """
        Load a tool function from a Python file.
        
        Args:
            file_path: Path to Python file containing tool
            
        Returns:
            Tool function if found, None otherwise
        """
        try:
            # Create module spec
            module_name = f"programmer_tools.{file_path.stem}"
            spec = importlib.util.spec_from_file_location(module_name, file_path)
            
            if spec is None or spec.loader is None:
                logger.warning(f"Could not create spec for {file_path}")
                return None
            
            # Load module
            module = importlib.util.module_from_spec(spec)
            sys.modules[module_name] = module
            spec.loader.exec_module(module)
            
            # Find tool functions in module
            tools_found = 0
            for name, obj in inspect.getmembers(module):
                if self._is_tool_function(name, obj):
                    # Store tool
                    self.loaded_tools[name] = obj
                    
                    # Extract metadata
                    metadata = self._extract_tool_metadata(name, obj)
                    self.tool_metadata[name] = metadata
                    
                    tools_found += 1
                    logger.info(f"  Loaded tool: {name} from {file_path.name}")
            
            if tools_found == 0:
                logger.warning(f"No tool functions found in {file_path.name}")
            
            return None
            
        except Exception as e:
            logger.error(f"Error loading tool from {file_path}: {e}", exc_info=True)
            return None
    
    def _is_tool_function(self, name: str, obj: Any) -> bool:
        """
        Check if an object is a tool function.
        
        Args:
            name: Object name
            obj: Python object
            
        Returns:
            True if this is a valid tool function
        """
        # Skip private functions
        if name.startswith("_"):
            return False
        
        # Skip common imports that aren't tools
        excluded_names = {
            'tool',  # LangChain decorator
            'logger',  # Logging object
            'Dict', 'Any', 'Optional', 'List',  # Type hints
            'Path', 'os', 'sys', 'logging',  # Standard library
            'pd', 'np', 'plt',  # Common abbreviations
        }
        if name in excluded_names:
            return False
        
        # Skip imported modules and classes
        if inspect.ismodule(obj) or inspect.isclass(obj):
            return False
        
        # Check for LangChain StructuredTool (from @tool decorator)
        # This is the ONLY valid non-function type we accept
        if hasattr(obj, 'name') and hasattr(obj, 'description') and hasattr(obj, 'args_schema'):
            # Verify it's actually a tool, not the decorator itself
            # The decorator won't have proper tool metadata
            if hasattr(obj, 'func') and callable(obj.func):
                return True
            return False
        
        # Must be a function
        if not inspect.isfunction(obj):
            return False
        
        return True
    
    def _extract_tool_metadata(self, name: str, obj: Any) -> Dict[str, Any]:
        """
        Extract metadata from a tool function.
        
        Args:
            name: Tool name
            obj: Tool function or StructuredTool
            
        Returns:
            Dict with tool metadata
        """
        metadata = {
            "name": name,
            "description": "",
            "parameters": {},
            "source": "programmer"
        }
        
        # Check if it's a LangChain StructuredTool
        if hasattr(obj, 'description') and hasattr(obj, 'args_schema'):
            metadata["name"] = obj.name
            metadata["description"] = obj.description or ""
            
            # Extract argument schema
            if obj.args_schema:
                schema = obj.args_schema.schema()
                if 'properties' in schema:
                    metadata["parameters"] = {
                        arg_name: {
                            "type": arg_props.get("type", "string"),
                            "description": arg_props.get("description", ""),
                            "required": arg_name in schema.get("required", [])
                        }
                        for arg_name, arg_props in schema['properties'].items()
                    }
        else:
            # Extract from function directly
            func = obj if inspect.isfunction(obj) else getattr(obj, 'func', None)
            
            if func:
                # Get docstring
                metadata["description"] = (func.__doc__ or "").strip()
                
                # Get signature
                try:
                    sig = inspect.signature(func)
                    for param_name, param in sig.parameters.items():
                        if param_name in ('self', 'cls', 'kwargs'):
                            continue
                        
                        metadata["parameters"][param_name] = {
                            "type": str(param.annotation) if param.annotation != inspect.Parameter.empty else "Any",
                            "default": str(param.default) if param.default != inspect.Parameter.empty else None,
                            "required": param.default == inspect.Parameter.empty
                        }
                except Exception as e:
                    logger.debug(f"Could not extract signature for {name}: {e}")
        
        return metadata
    
    def get_tools_for_agent(self, agent_name: str = "all") -> Dict[str, Callable]:
        """
        Get programmer-generated tools suitable for a specific agent.
        
        Args:
            agent_name: Name of agent requesting tools (analysis, hpc, etc.)
            
        Returns:
            Dict of tool name -> function
        """
        # For now, return all tools to all agents
        # In future, could filter based on tool metadata
        return self.loaded_tools.copy()
    
    def get_tool_metadata_list(self) -> List[Dict[str, Any]]:
        """
        Get metadata for all loaded tools.
        
        Returns:
            List of tool metadata dicts
        """
        return list(self.tool_metadata.values())
    
    def reload_tools(self) -> int:
        """
        Reload all tools from programmer directory.
        
        Returns:
            Number of tools loaded
        """
        self.loaded_tools.clear()
        self.tool_metadata.clear()
        self.discover_and_load_tools()
        return len(self.loaded_tools)


# Global instance for easy access
_global_loader: Optional[DynamicToolLoader] = None


def get_dynamic_tool_loader(programmer_dir: str = "working_dir/programmer", refresh: bool = False) -> DynamicToolLoader:
    """
    Get or create global dynamic tool loader instance.
    
    Args:
        programmer_dir: Directory containing programmer-generated tools
        refresh: If True, reload all tools from disk
        
    Returns:
        DynamicToolLoader instance
    """
    global _global_loader
    
    if _global_loader is None or refresh:
        _global_loader = DynamicToolLoader(programmer_dir)
        _global_loader.discover_and_load_tools()
    
    return _global_loader
