"""
Pydantic schemas for preprocessing tools and LLM agent calls.
Enables structured tool calling with LLM agents.
"""
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class PDBAnalysisResult(BaseModel):
    """Result of PDB file analysis"""
    file_exists: bool = Field(description="Whether the PDB file exists")
    atom_count: int = Field(default=0, description="Number of atoms")
    residue_count: int = Field(default=0, description="Number of residues")
    chain_count: int = Field(default=0, description="Number of chains")
    has_waters: bool = Field(default=False, description="Contains water molecules (HOH, WAT)")
    has_heteroatoms: bool = Field(default=False, description="Contains heteroatoms (ligands, ions)")
    heteroatoms: List[str] = Field(default_factory=list, description="List of heteroatom types")
    alternate_locations: bool = Field(default=False, description="Contains alternate conformations")
    missing_hydrogens: bool = Field(default=True, description="Missing hydrogen atoms")
    chain_ids: List[str] = Field(default_factory=list, description="Chain identifiers")


class PreprocessingStep(BaseModel):
    """Single preprocessing step to execute"""
    name: str = Field(description="Step name (e.g., 'remove_waters', 'add_hydrogens')")
    description: str = Field(description="Human-readable description of the step")
    command: Optional[str] = Field(default=None, description="Shell command to execute")
    tool_name: Optional[str] = Field(default=None, description="Tool/function name to call")
    tool_params: Dict[str, Any] = Field(default_factory=dict, description="Parameters for tool")
    input_file: Optional[str] = Field(default=None, description="Input file for this step")
    output_file: Optional[str] = Field(default=None, description="Output file from this step")
    reason: str = Field(description="Why this step is needed")
    

class PreprocessingPlan(BaseModel):
    """Complete preprocessing plan generated by LLM"""
    reasoning: str = Field(description="Detailed reasoning for the preprocessing strategy")
    overview: str = Field(description="High-level overview of the plan")
    steps: List[PreprocessingStep] = Field(description="Ordered list of preprocessing steps")
    estimated_output_files: Dict[str, str] = Field(
        default_factory=dict, 
        description="Expected output files and their descriptions"
    )
    potential_issues: List[str] = Field(default_factory=list, description="Potential issues to watch for")
    recommendations: List[str] = Field(default_factory=list, description="Post-processing recommendations")
    

class PreprocessingToolCall(BaseModel):
    """Tool call request from LLM agent"""
    tool_name: str = Field(description="Name of the tool to call")
    parameters: Dict[str, Any] = Field(description="Parameters for the tool")
    description: str = Field(description="What this tool call will do")
    

class PreprocessingResult(BaseModel):
    """Result of preprocessing execution"""
    success: bool = Field(description="Whether preprocessing succeeded")
    cleaned_pdb: Optional[str] = Field(default=None, description="Path to cleaned PDB file")
    topology: Optional[str] = Field(default=None, description="Path to GROMACS topology")
    processed_coordinates: Optional[str] = Field(default=None, description="Path to processed coordinates")
    report: str = Field(description="Detailed execution report")
    issues: List[str] = Field(default_factory=list, description="Issues encountered")
    warnings: List[str] = Field(default_factory=list, description="Warnings from processing")
    generated_files: Dict[str, str] = Field(
        default_factory=dict,
        description="Map of all generated files and their descriptions"
    )
    ligand_files: List[str] = Field(default_factory=list, description="Paths to ligand PDB files")
    ligand_resnames: List[str] = Field(default_factory=list, description="Ligand residue names (e.g. ATP, GTP)")
    ion_files: List[str] = Field(default_factory=list, description="Paths to ion PDB files")
    ion_resnames: List[str] = Field(default_factory=list, description="Ion residue names (e.g. MG, ZN)")
    execution_log: str = Field(default="", description="Log of all commands executed")


class PreprocessingAgentInput(BaseModel):
    """Input to preprocessing agent"""
    pdb_path: str = Field(description="Path to input PDB file")
    working_directory: str = Field(description="Working directory for output files")
    force_field: str = Field(description="Force field to use (e.g., 'amber99sb-ildn')")
    water_model: str = Field(description="Water model (e.g., 'tip3p')")
    remove_waters: bool = Field(default=True, description="Whether to remove water molecules")
    add_hydrogens: bool = Field(default=True, description="Whether to add missing hydrogens")
    user_goal: str = Field(description="Original user goal/request")
    additional_instructions: Optional[str] = Field(
        default=None,
        description="Any additional instructions from user"
    )
    component_selection: Optional[Dict[str, Any]] = Field(
        default=None,
        description="User-specified component selection: {protein: bool, ligand: bool, ions: bool, water: bool}"
    )


class PreprocessingAgentOutput(BaseModel):
    """Output from preprocessing agent"""
    success: bool = Field(description="Whether preprocessing succeeded")
    plan: PreprocessingPlan = Field(description="The preprocessing plan that was executed")
    result: PreprocessingResult = Field(description="Result of execution")
    supervisor_update: Dict[str, Any] = Field(
        description="State updates to send back to supervisor"
    )
