"""
Reporter Agent Tools

Tools for reading analysis summaries, searching scientific literature,
and generating comprehensive HTML reports.
"""
import os
import json
import logging
import base64
from typing import Dict, Any, List, Optional
from pathlib import Path
from datetime import datetime
from langchain.tools import tool

logger = logging.getLogger(__name__)


# ==================== Analysis Summary Tools ====================

@tool
def read_analysis_summary(
    summary_file: str,
    working_dir: Optional[str] = None
) -> Dict[str, Any]:
    """
    Read and parse analysis_summary.jsonl file.
    
    Extracts all analysis results, statistics, and metadata from the
    JSONL file generated by the analysis agent.
    
    Args:
        summary_file: Path to analysis_summary.jsonl (can be filename or full path)
        working_dir: Working directory (if summary_file is relative)
    
    Returns:
        Dict with parsed analysis entries and summary statistics
    """
    # Resolve input path
    from ..utils import resolve_input_path
    summary_path = resolve_input_path(summary_file, "summary_file", working_dir)
    
    if not summary_path.exists():
        logger.error(f"Analysis summary file not found: {summary_path}")
        return {
            "success": False,
            "error": f"File not found: {summary_path}",
            "entries": [],
            "summary": {}
        }
    
    try:
        entries = []
        with open(summary_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line:
                    entry = json.loads(line)
                    entries.append(entry)
        
        # Summarize analysis types
        analysis_types = {}
        for entry in entries:
            atype = entry.get("analysis_type", "unknown")
            if atype not in analysis_types:
                analysis_types[atype] = 0
            analysis_types[atype] += 1
        
        logger.info(f"Read {len(entries)} analysis entries from {summary_path}")
        
        return {
            "success": True,
            "file_path": str(summary_path),
            "total_entries": len(entries),
            "entries": entries,
            "analysis_types": analysis_types,
            "timestamp": datetime.now().isoformat()
        }
        
    except Exception as e:
        logger.error(f"Error reading analysis summary: {e}", exc_info=True)
        return {
            "success": False,
            "error": str(e),
            "entries": [],
            "summary": {}
        }


# ==================== Literature Search Tools ====================

@tool
def search_pubmed(
    query: str,
    max_results: int = 10,
    include_abstracts: bool = True,
    max_age_years: Optional[int] = 10
) -> Dict[str, Any]:
    """
    Search PubMed for scientific literature.
    
    Uses the NCBI E-utilities API to search PubMed and retrieve
    article metadata, abstracts, and citations.
    
    Args:
        query: Search query string
        max_results: Maximum number of results to return
        include_abstracts: Whether to fetch full abstracts
        max_age_years: Limit to papers from last N years (None for no limit)
    
    Returns:
        Dict with search results and metadata
    """
    try:
        from Bio import Entrez
        Entrez.email = "md.workflow@example.com"  # Required by NCBI
        
        # Build search term with date filter
        search_term = query
        if max_age_years:
            from datetime import datetime
            current_year = datetime.now().year
            min_year = current_year - max_age_years
            search_term += f" AND {min_year}[PDAT]:{current_year}[PDAT]"
        
        logger.info(f"Searching PubMed: {search_term}")
        
        # Search PubMed
        handle = Entrez.esearch(
            db="pubmed",
            term=search_term,
            retmax=max_results,
            sort="relevance"
        )
        search_results = Entrez.read(handle)
        handle.close()
        
        pmids = search_results.get("IdList", [])
        logger.info(f"Found {len(pmids)} results")
        
        if not pmids:
            return {
                "success": True,
                "query": query,
                "total_found": 0,
                "results": []
            }
        
        # Fetch article details
        if include_abstracts:
            handle = Entrez.efetch(
                db="pubmed",
                id=pmids,
                rettype="medline",
                retmode="xml"
            )
            records = Entrez.read(handle)
            handle.close()
            
            articles = []
            for article in records.get("PubmedArticle", []):
                try:
                    medline = article.get("MedlineCitation", {})
                    article_data = medline.get("Article", {})
                    
                    # Extract authors
                    author_list = article_data.get("AuthorList", [])
                    authors = []
                    for author in author_list[:10]:  # Max 10 authors
                        if "LastName" in author and "Initials" in author:
                            authors.append(f"{author['LastName']} {author['Initials']}")
                    
                    # Extract abstract
                    abstract_data = article_data.get("Abstract", {})
                    abstract_texts = abstract_data.get("AbstractText", [])
                    abstract = " ".join([str(text) for text in abstract_texts]) if abstract_texts else None
                    
                    # Extract journal info
                    journal = article_data.get("Journal", {})
                    journal_title = journal.get("Title", "Unknown")
                    pub_date = journal.get("JournalIssue", {}).get("PubDate", {})
                    year = pub_date.get("Year", None)
                    
                    # Extract IDs
                    pmid = medline.get("PMID", None)
                    article_ids = article.get("PubmedData", {}).get("ArticleIdList", [])
                    doi = None
                    for aid in article_ids:
                        if aid.attributes.get("IdType") == "doi":
                            doi = str(aid)
                            break
                    
                    articles.append({
                        "title": article_data.get("ArticleTitle", "Unknown"),
                        "authors": authors,
                        "journal": journal_title,
                        "year": int(year) if year else None,
                        "pmid": str(pmid) if pmid else None,
                        "doi": doi,
                        "abstract": abstract,
                        "url": f"https://pubmed.ncbi.nlm.nih.gov/{pmid}/" if pmid else None
                    })
                    
                except Exception as e:
                    logger.warning(f"Error parsing article: {e}")
                    continue
            
            return {
                "success": True,
                "query": query,
                "total_found": len(pmids),
                "returned": len(articles),
                "results": articles
            }
        else:
            # Just return PMIDs without abstracts
            return {
                "success": True,
                "query": query,
                "total_found": len(pmids),
                "pmids": [str(pmid) for pmid in pmids],
                "results": []
            }
            
    except ImportError:
        logger.error("Biopython not installed - PubMed search unavailable")
        return {
            "success": False,
            "error": "Biopython not installed. Install with: pip install biopython",
            "results": []
        }
    except Exception as e:
        logger.error(f"PubMed search error: {e}", exc_info=True)
        return {
            "success": False,
            "error": str(e),
            "results": []
        }


@tool
def generate_literature_queries(
    analysis_types: List[str],
    user_goal: Optional[str] = None
) -> Dict[str, Any]:
    """
    Generate PubMed search queries based on analysis types.
    
    Creates optimized search queries for each analysis type to find
    relevant literature automatically.
    
    Args:
        analysis_types: List of analysis types performed (e.g., ["RMSD", "RMSF"])
        user_goal: User's original goal/question (optional, helps refine queries)
    
    Returns:
        Dict with generated queries for each analysis type
    """
    # Default query templates
    query_templates = {
        "RMSD": "root mean square deviation molecular dynamics protein stability",
        "RMSF": "root mean square fluctuation residue flexibility protein dynamics",
        "Radius_of_Gyration": "radius of gyration protein compactness folding",
        "Energy": "molecular dynamics energy stability thermodynamic analysis",
        "SASA": "solvent accessible surface area protein binding interface",
        "Secondary_Structure": "secondary structure DSSP molecular dynamics",
        "COM_Analysis": "center of mass protein motion trajectory analysis"
    }
    
    queries = {}
    for atype in analysis_types:
        # Match analysis type (case-insensitive, flexible matching)
        matched = False
        for template_key in query_templates:
            if template_key.lower() in atype.lower() or atype.lower() in template_key.lower():
                queries[atype] = query_templates[template_key]
                matched = True
                break
        
        if not matched:
            # Generic query for unknown analysis types
            queries[atype] = f"{atype} molecular dynamics simulation analysis"
    
    # Add user goal context if provided
    if user_goal:
        # Extract key terms from user goal (simplified)
        user_terms = [word for word in user_goal.lower().split() 
                      if len(word) > 4 and word not in ["analysis", "please", "could", "would"]]
        if user_terms:
            context = " ".join(user_terms[:3])  # Max 3 terms
            for atype in queries:
                queries[atype] += f" {context}"
    
    logger.info(f"Generated {len(queries)} literature queries")
    
    return {
        "success": True,
        "queries": queries,
        "total": len(queries)
    }


# ==================== Report Generation Tools ====================

@tool
def generate_html_report(
    analysis_data: Dict[str, Any],
    literature_refs: Optional[List[Dict[str, Any]]] = None,
    report_type: str = "comprehensive",
    output_file: str = "report.html",
    working_dir: Optional[str] = None
) -> Dict[str, Any]:
    """
    Generate HTML report from analysis data and literature.
    
    Creates a professional scientific report with analysis results,
    visualizations, and literature context.
    
    Args:
        analysis_data: Parsed analysis summary data
        literature_refs: List of literature references (optional)
        report_type: Type of report ("comprehensive" or "executive")
        output_file: Output HTML filename (saved in working_dir)
        working_dir: Working directory for output
    
    Returns:
        Dict with report generation results
    """
    if working_dir is None:
        working_dir = os.getcwd()
    
    output_path = Path(working_dir) / output_file
    
    try:
        # Build HTML content
        html_content = _build_html_report(
            analysis_data=analysis_data,
            literature_refs=literature_refs or [],
            report_type=report_type
        )
        
        # Write to file
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        logger.info(f"Generated HTML report: {output_path}")
        
        return {
            "success": True,
            "report_file": str(output_path),
            "report_type": report_type,
            "file_size_kb": output_path.stat().st_size / 1024
        }
        
    except Exception as e:
        logger.error(f"Error generating HTML report: {e}", exc_info=True)
        return {
            "success": False,
            "error": str(e)
        }


def _build_html_report(
    analysis_data: Dict[str, Any],
    literature_refs: List[Dict[str, Any]],
    report_type: str
) -> str:
    """Build HTML content for report"""
    
    # Extract data
    entries = analysis_data.get("entries", [])
    analysis_types = analysis_data.get("analysis_types", {})
    
    # Build HTML
    html_parts = []
    
    # HTML header
    html_parts.append("""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Molecular Dynamics Analysis Report</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .container {
            background-color: white;
            padding: 40px;
            box-shadow: 0 0 20px rgba(0,0,0,0.1);
            border-radius: 8px;
        }
        h1 {
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }
        h2 {
            color: #34495e;
            margin-top: 30px;
            border-bottom: 2px solid #ecf0f1;
            padding-bottom: 8px;
        }
        h3 {
            color: #7f8c8d;
        }
        .metadata {
            background-color: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
            margin: 20px 0;
        }
        .analysis-section {
            margin: 30px 0;
            padding: 20px;
            border-left: 4px solid #3498db;
            background-color: #f8f9fa;
        }
        .statistics {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
            margin: 20px 0;
        }
        .stat-box {
            background-color: white;
            padding: 15px;
            border-radius: 5px;
            border: 1px solid #ddd;
            text-align: center;
        }
        .stat-value {
            font-size: 24px;
            font-weight: bold;
            color: #3498db;
        }
        .stat-label {
            font-size: 12px;
            color: #7f8c8d;
            text-transform: uppercase;
        }
        .reference {
            margin: 10px 0;
            padding: 10px;
            background-color: #f8f9fa;
            border-left: 3px solid #95a5a6;
        }
        .reference-title {
            font-weight: bold;
            color: #2c3e50;
        }
        .reference-authors {
            font-style: italic;
            color: #7f8c8d;
            font-size: 14px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #3498db;
            color: white;
        }
        tr:hover {
            background-color: #f5f5f5;
        }
        .timestamp {
            color: #95a5a6;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="container">
""")
    
    # Title and metadata
    html_parts.append("<h1>Molecular Dynamics Analysis Report</h1>")
    html_parts.append(f'<div class="metadata">')
    html_parts.append(f'<p><strong>Report Type:</strong> {report_type.title()}</p>')
    html_parts.append(f'<p><strong>Generated:</strong> {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>')
    html_parts.append(f'<p><strong>Total Analyses:</strong> {len(entries)}</p>')
    html_parts.append(f'<p><strong>Analysis Types:</strong> {", ".join(analysis_types.keys())}</p>')
    html_parts.append('</div>')
    
    # Analysis sections
    html_parts.append("<h2>Analysis Results</h2>")
    
    for entry in entries:
        atype = entry.get("analysis_type", "Unknown")
        stats = entry.get("statistics", {})
        files = entry.get("files", {})
        metadata = entry.get("metadata", {})
        timestamp = entry.get("timestamp", "")
        
        html_parts.append(f'<div class="analysis-section">')
        html_parts.append(f'<h3>{atype}</h3>')
        html_parts.append(f'<p class="timestamp">Performed: {timestamp}</p>')
        
        # Statistics
        if stats:
            html_parts.append('<div class="statistics">')
            for key, value in stats.items():
                if isinstance(value, (int, float)):
                    formatted_value = f"{value:.4f}" if isinstance(value, float) else str(value)
                    html_parts.append(f'''
                        <div class="stat-box">
                            <div class="stat-value">{formatted_value}</div>
                            <div class="stat-label">{key.replace("_", " ")}</div>
                        </div>
                    ''')
            html_parts.append('</div>')
        
        # Files
        if files:
            html_parts.append('<p><strong>Generated Files:</strong></p>')
            html_parts.append('<ul>')
            for file_type, file_path in files.items():
                html_parts.append(f'<li><strong>{file_type}:</strong> {file_path}</li>')
            html_parts.append('</ul>')
        
        # Metadata
        if metadata:
            html_parts.append('<p><strong>Additional Information:</strong></p>')
            html_parts.append('<ul>')
            for key, value in metadata.items():
                html_parts.append(f'<li><strong>{key}:</strong> {value}</li>')
            html_parts.append('</ul>')
        
        html_parts.append('</div>')
    
    # Literature references
    if literature_refs:
        html_parts.append("<h2>Scientific Literature</h2>")
        html_parts.append(f'<p>Found {len(literature_refs)} relevant publications:</p>')
        
        for idx, ref in enumerate(literature_refs, 1):
            html_parts.append(f'<div class="reference">')
            html_parts.append(f'<div class="reference-title">[{idx}] {ref.get("title", "Unknown")}</div>')
            
            authors = ref.get("authors", [])
            if authors:
                author_str = ", ".join(authors[:3])
                if len(authors) > 3:
                    author_str += " et al."
                html_parts.append(f'<div class="reference-authors">{author_str}</div>')
            
            journal = ref.get("journal", "")
            year = ref.get("year", "")
            if journal or year:
                html_parts.append(f'<p><em>{journal}</em> ({year})</p>')
            
            doi = ref.get("doi")
            if doi:
                html_parts.append(f'<p>DOI: <a href="https://doi.org/{doi}">{doi}</a></p>')
            
            pmid = ref.get("pmid")
            if pmid:
                html_parts.append(f'<p>PMID: <a href="https://pubmed.ncbi.nlm.nih.gov/{pmid}/">{pmid}</a></p>')
            
            abstract = ref.get("abstract")
            if abstract and len(abstract) > 100:
                # Truncate long abstracts
                abstract_preview = abstract[:300] + "..."
                html_parts.append(f'<p><strong>Abstract:</strong> {abstract_preview}</p>')
            
            html_parts.append('</div>')
    
    # Footer
    html_parts.append("""
    </div>
</body>
</html>
""")
    
    return "\n".join(html_parts)


# ==================== Tool Executor ====================

class ReporterToolExecutor:
    """Executor for reporter tools"""
    
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.working_dir = config.get("working_directory", os.getcwd())
        logger.info(f"Reporter tool executor initialized (working_dir: {self.working_dir})")
    
    def execute_tool(self, tool_name: str, tool_params: Dict[str, Any]) -> Dict[str, Any]:
        """Execute a reporter tool by name"""
        
        # Map tool names to functions
        tools_map = {
            "read_analysis_summary": read_analysis_summary,
            "search_pubmed": search_pubmed,
            "generate_literature_queries": generate_literature_queries,
            "generate_html_report": generate_html_report
        }
        
        if tool_name not in tools_map:
            return {
                "success": False,
                "error": f"Unknown tool: {tool_name}",
                "available_tools": list(tools_map.keys())
            }
        
        try:
            # Add working_dir to params if not present
            if "working_dir" not in tool_params and "working_dir" in globals()[tool_name].func.__code__.co_varnames:
                tool_params["working_dir"] = self.working_dir
            
            # Execute tool
            tool_func = tools_map[tool_name]
            result = tool_func.invoke(tool_params)
            
            return result if isinstance(result, dict) else {"result": result}
            
        except Exception as e:
            logger.error(f"Error executing tool {tool_name}: {e}", exc_info=True)
            return {
                "success": False,
                "error": str(e),
                "tool": tool_name
            }


def get_tool_metadata() -> Dict[str, Dict[str, Any]]:
    """Get metadata for all reporter tools"""
    return {
        "read_analysis_summary": {
            "description": "Read and parse analysis_summary.jsonl file",
            "parameters": ["summary_file", "working_dir"]
        },
        "search_pubmed": {
            "description": "Search PubMed for scientific literature",
            "parameters": ["query", "max_results", "include_abstracts", "max_age_years"]
        },
        "generate_literature_queries": {
            "description": "Generate PubMed queries from analysis types",
            "parameters": ["analysis_types", "user_goal"]
        },
        "generate_html_report": {
            "description": "Generate HTML report from analysis data",
            "parameters": ["analysis_data", "literature_refs", "report_type", "output_file", "working_dir"]
        }
    }
